development:
  perform_authentication: true
  STORMSAVVY_GMAIL_USERNAME: alerts@stormsavvy.com
  STORMSAVVY_GMAIL_PASSWORD: DarkAndStormy
  AWS_ACCESS_KEY_ID: AKIAI2XLVAVUZ6BBZ3ZA
  AWS_BUCKET: stormsavvy
  AWS_SECRET_ACCESS_KEY: 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

test:
  perform_authentication: true
  STORMSAVVY_GMAIL_USERNAME: alerts@stormsavvy.com
  STORMSAVVY_GMAIL_PASSWORD: DarkAndStormy

production:
  perform_authentication: false
  STRIPE_API_KEY: sk_live_7GfB1PylLNMf8v26RITa95Iu
  STRIPE_PUBLIC_KEY: pk_live_GBRP0mjjNUNrr8n2coIa0Z0f
